/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    blogCategories: BlogCategory;
    portfolioCategories: PortfolioCategory;
    posts: Post;
    tags: Tag;
    media: Media;
    items: Item;
    pages: Page;
    studies: Study;
    categories: Category;
    users: User;
  };
  globals: {
    footer: Footer;
    'main-menu': MainMenu;
  };
}
export interface BlogCategory {
  id: string;
  name?: string;
}
export interface PortfolioCategory {
  id: string;
  name?: string;
}
export interface Post {
  id: string;
  title?: string;
  publishedDate?: string;
  category?: string | BlogCategory;
  tags?: string[] | Tag[];
  content?: {
    [k: string]: unknown;
  }[];
  status?: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
export interface Tag {
  id: string;
  name?: string;
}
export interface Media {
  id: string;
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
  sizes?: {
    thumbnail?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
    sixteenByNineMedium?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
  };
}
export interface Item {
  id: string;
  name?: string;
  description?: string;
  category?: string | PortfolioCategory;
  thumbnail?: string | Media;
}
export interface Page {
  id: string;
  title: string;
  heroType: 'minimal' | 'contentAboveMedia' | 'contentLeftOfMedia';
  heroContent: {
    [k: string]: unknown;
  }[];
  heroMedia: string | Media;
  layout?: (
    | {
        backgroundColor?: 'none' | 'red' | 'blue' | 'orange';
        content: {
          [k: string]: unknown;
        }[];
        actions?: {
          link: {
            type?: 'page' | 'custom';
            label: string;
            page: string | Page;
            url: string;
          };
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'call-to-action';
      }
    | {
        backgroundColor?: 'none' | 'red' | 'blue' | 'orange';
        columns?: {
          width: 'oneThird' | 'half' | 'twoThirds' | 'full';
          alignment: 'left' | 'center' | 'right';
          content: {
            [k: string]: unknown;
          }[];
          id?: string;
        }[];
        accentLine?: boolean;
        accentLineAlignment?: 'left' | 'right';
        paddingTop?: 'none' | 'small' | 'medium' | 'large';
        paddingBottom?: 'none' | 'small' | 'medium' | 'large';
        id?: string;
        blockName?: string;
        blockType: 'content';
      }
    | {
        actions?: {
          headline: string;
          icon?: 'none' | 'arrow';
          link: {
            type?: 'page' | 'custom';
            label: string;
            page: string | Page;
            url: string;
          };
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'cta-grid';
      }
    | {
        mediaFields: {
          position?: 'default' | 'wide';
          media: string | Media;
          caption?: {
            [k: string]: unknown;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'Media';
      }
    | {
        media?: {
          media: string | Media;
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'media-collage';
      }
    | {
        backgroundColor?: 'none' | 'red' | 'blue' | 'orange';
        content: {
          [k: string]: unknown;
        }[];
        enableCTA?: boolean;
        link?: {
          type?: 'page' | 'custom';
          label: string;
          page: string | Page;
          url: string;
        };
        media?: {
          media: string | Media;
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'media-content-collage';
      }
    | {
        backgroundColor?: 'none' | 'red' | 'blue' | 'orange';
        content?: {
          [k: string]: unknown;
        }[];
        media?: {
          media: string | Media;
          content?: string;
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'media-grid';
      }
    | {
        topOverlap?: 'none' | 'small' | 'medium' | 'large';
        bottomOverlap?: 'none' | 'small' | 'medium' | 'large';
        stats?: {
          stat?: string;
          description?: string;
          id?: string;
        }[];
        media?: {
          media: string | Media;
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'media-stat-collage';
      }
    | {
        backgroundColor?: 'none' | 'red' | 'blue' | 'orange';
        slides?: {
          media: string | Media;
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'slider';
      }
    | {
        size: 'small' | 'medium' | 'large';
        id?: string;
        blockName?: string;
        blockType: 'spacer';
      }
    | {
        sections?: {
          label: string;
          description: string;
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'sticky-content';
      }
    | {
        backgroundColor?: 'none' | 'red' | 'blue' | 'orange';
        studies: string[] | Study[];
        id?: string;
        blockName?: string;
        blockType: 'study-slider';
      }
  )[];
  meta?: {
    title?: string;
    description?: string;
    keywords?: string;
  };
  slug?: string;
  updatedAt: string;
  createdAt: string;
}
export interface Study {
  id: string;
  title: string;
  featuredMedia: string | Media;
  layout?: (
    | {
        backgroundColor?: 'none' | 'red' | 'blue' | 'orange';
        content: {
          [k: string]: unknown;
        }[];
        actions?: {
          link: {
            type?: 'page' | 'custom';
            label: string;
            page: string | Page;
            url: string;
          };
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'call-to-action';
      }
    | {
        backgroundColor?: 'none' | 'red' | 'blue' | 'orange';
        columns?: {
          width: 'oneThird' | 'half' | 'twoThirds' | 'full';
          alignment: 'left' | 'center' | 'right';
          content: {
            [k: string]: unknown;
          }[];
          id?: string;
        }[];
        accentLine?: boolean;
        accentLineAlignment?: 'left' | 'right';
        paddingTop?: 'none' | 'small' | 'medium' | 'large';
        paddingBottom?: 'none' | 'small' | 'medium' | 'large';
        id?: string;
        blockName?: string;
        blockType: 'content';
      }
    | {
        actions?: {
          headline: string;
          icon?: 'none' | 'arrow';
          link: {
            type?: 'page' | 'custom';
            label: string;
            page: string | Page;
            url: string;
          };
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'cta-grid';
      }
    | {
        mediaFields: {
          position?: 'default' | 'wide';
          media: string | Media;
          caption?: {
            [k: string]: unknown;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'Media';
      }
    | {
        media?: {
          media: string | Media;
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'media-collage';
      }
    | {
        backgroundColor?: 'none' | 'red' | 'blue' | 'orange';
        content: {
          [k: string]: unknown;
        }[];
        enableCTA?: boolean;
        link?: {
          type?: 'page' | 'custom';
          label: string;
          page: string | Page;
          url: string;
        };
        media?: {
          media: string | Media;
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'media-content-collage';
      }
    | {
        backgroundColor?: 'none' | 'red' | 'blue' | 'orange';
        content?: {
          [k: string]: unknown;
        }[];
        media?: {
          media: string | Media;
          content?: string;
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'media-grid';
      }
    | {
        topOverlap?: 'none' | 'small' | 'medium' | 'large';
        bottomOverlap?: 'none' | 'small' | 'medium' | 'large';
        stats?: {
          stat?: string;
          description?: string;
          id?: string;
        }[];
        media?: {
          media: string | Media;
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'media-stat-collage';
      }
    | {
        backgroundColor?: 'none' | 'red' | 'blue' | 'orange';
        slides?: {
          media: string | Media;
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'slider';
      }
    | {
        size: 'small' | 'medium' | 'large';
        id?: string;
        blockName?: string;
        blockType: 'spacer';
      }
    | {
        backgroundColor?: 'none' | 'red' | 'blue' | 'orange';
        topOverlap?: 'none' | 'small' | 'medium' | 'large';
        bottomOverlap?: 'none' | 'small' | 'medium' | 'large';
        stats?: {
          stat?: string;
          description?: string;
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'statistics';
      }
    | {
        sections?: {
          label: string;
          description: string;
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'sticky-content';
      }
    | {
        backgroundColor?: 'none' | 'red' | 'blue' | 'orange';
        studies: string[] | Study[];
        id?: string;
        blockName?: string;
        blockType: 'study-slider';
      }
  )[];
  previewMedia?: {
    media: string | Media;
    id?: string;
  }[];
  client?: string;
  location?: string;
  categories?: string[] | Category[];
  slug?: string;
  meta?: {
    title?: string;
    description?: string;
    keywords?: string;
  };
  updatedAt: string;
  createdAt: string;
}
export interface Category {
  id: string;
  title: string;
  slug?: string;
  updatedAt: string;
  createdAt: string;
}
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface Footer {
  id: string;
  columns?: {
    navItems?: {
      link: {
        type?: 'page' | 'custom';
        label: string;
        page: string | Page;
        url: string;
      };
      id?: string;
    }[];
    id?: string;
  }[];
  updatedAt?: string;
  createdAt?: string;
}
export interface MainMenu {
  id: string;
  navItems?: {
    link: {
      type?: 'page' | 'custom';
      label: string;
      page: string | Page;
      url: string;
    };
    id?: string;
  }[];
  updatedAt?: string;
  createdAt?: string;
}
